version: "3"

services:
  users:
    build:
      context: ./Users
      dockerfile: Dockerfile
    depends_on:
      - scylladb
      - consul
      - jaegar
      - messages
    ports:
      - 8000:8000

  messages:
    build:
      context: ./Messages
      dockerfile: Dockerfile
    depends_on:
      - scylladb
      - consul
      - jaegar
    ports:
      - 8001:8001
      - 50051:50051

  scylladb:
    image: scylladb/scylla
    ports:
      - 9042:9042

  consul:
    image: consul:1.11.1
    restart: always
    ports:
      - 8500:8500

  jaegar:
    image: jaegertracing/all-in-one:1.29
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14250:14250 
      - 14268:14268 
      - 14269:14269 
      - 9411:9411
